// src/js/species.js
// Animal species, linked to classId, with general properties
// Sample data for demo purposes

export const species = [
  {
    id: 's1',
    name: 'Dog',
    classId: 'c1',
    lifeSpan: [8, 15],
    size: 'varied',
    cost: { initial: [500, 2000], adoption: [150, 500], monthly: [80, 150] },
    habitat: {
      housing: ['apartment', 'house'],
      space: 'varied',
      climate: ['varied'],
    },
    care: {
      social: 'varied',
      grooming: 'varied',
      exercise: 'varied',
      training: 'varied',
    },
    temperament: ['varied'],
    goodWithChildren: null,
    goodWithOtherPets: null,
    image:
      'https://cdn.pixabay.com/photo/2023/10/01/12/27/border-collie-8287329_1280.jpg',
    imageAlt: 'A happy border collie',
  },
  {
    id: 's2',
    name: 'Cat',
    classId: 'c1',
    lifeSpan: [12, 18],
    size: 'varied',
    cost: { initial: [300, 1200], adoption: [75, 250], monthly: [40, 100] },
    habitat: {
      housing: ['apartment', 'house', 'farm'],
      space: 'varied',
      climate: ['varied'],
    },
    care: {
      social: 'varied',
      grooming: 'varied',
      exercise: 'varied',
      training: 'varied',
    },
    temperament: ['varied'],
    goodWithChildren: null,
    goodWithOtherPets: null,
    image:
      'https://cdn.pixabay.com/photo/2019/05/08/21/21/cat-4189697_1280.jpg',
    imageAlt: 'A tabby cat sleeping in the arms of a person',
  },
  {
    id: 's3',
    name: 'Budgerigar',
    classId: 'c2',
    lifeSpan: [5, 15],
    size: 'small',
    cost: { initial: [10, 150], adoption: [20, 60], monthly: [20, 50] },
    habitat: {
      housing: ['cage'],
      space: 'small',
      climate: ['temperate', 'warm'],
    },
    care: {
      social: 'social',
      grooming: 'low',
      exercise: 'moderate',
      training: 'moderate',
    },
    temperament: ['friendly', 'playful', 'vocal'],
    goodWithChildren: true,
    goodWithOtherPets: null,
    image:
      'https://cdn.pixabay.com/photo/2023/02/24/15/16/bird-7811343_1280.jpg',
    imageAlt: 'A colorful budgerigar perched on a branch',
  },
  {
    id: 's4',
    name: 'Rabbit',
    classId: 'c1',
    lifeSpan: [8, 12],
    size: 'small',
    cost: { initial: [150, 300], adoption: [30, 75], monthly: [30, 60] },
    habitat: {
      housing: ['enclosure', 'farm'],
      space: 'small',
      climate: ['temperate'],
    },
    care: {
      social: 'social',
      grooming: 'moderate',
      exercise: 'moderate',
      training: 'moderate',
    },
    temperament: ['gentle', 'curious', 'quiet'],
    goodWithChildren: true,
    goodWithOtherPets: null,
    image:
      'https://cdn.pixabay.com/photo/2020/10/13/18/48/rabbit-5652587_1280.jpg',
    imageAlt: 'A brown rabbit sitting in the grass',
  },
  {
    id: 's5',
    name: 'Central Bearded Dragon',
    classId: 'c3',
    lifeSpan: [8, 12],
    size: 'medium',
    cost: { initial: [200, 500], adoption: [50, 150], monthly: [25, 40] },
    habitat: {
      housing: ['terrarium'],
      space: 'small',
      climate: ['warm'],
    },
    care: {
      social: 'solitary',
      grooming: 'low',
      exercise: 'low',
      training: 'moderate',
    },
    temperament: ['docile', 'friendly', 'calm'],
    goodWithChildren: false,
    goodWithOtherPets: false,
    image:
      'https://cdn.pixabay.com/photo/2017/10/02/22/59/zoo-2810671_1280.jpg',
    imageAlt: 'A central bearded dragon',
  },
  {
    id: 's6',
    name: 'Goldfish',
    classId: 'c4',
    lifeSpan: [5, 10],
    size: 'small',
    cost: { initial: [20, 80], adoption: [5, 20], monthly: [10, 20] },
    habitat: {
      housing: ['aquarium'],
      space: 'small',
      climate: ['temperate'],
    },
    care: {
      social: 'solitary',
      grooming: 'none',
      exercise: 'low',
      training: 'easy',
    },
    temperament: ['peaceful', 'gentle'],
    goodWithChildren: true,
    goodWithOtherPets: null,
    image:
      'https://cdn.pixabay.com/photo/2017/04/04/17/34/food-2202364_1280.jpg',
    imageAlt: 'Goldfish crackers',
  },
  {
    id: 's7',
    name: 'Australian Green Tree Frog',
    classId: 'c5',
    lifeSpan: [10, 15],
    size: 'small',
    cost: { initial: [60, 140], adoption: [15, 35], monthly: [15, 30] },
    habitat: {
      housing: ['terrarium'],
      space: 'small',
      climate: ['warm', 'humid'],
    },
    care: {
      social: 'solitary',
      grooming: 'none',
      exercise: 'low',
      training: 'easy',
    },
    temperament: ['calm', 'easygoing'],
    goodWithChildren: true,
    goodWithOtherPets: null,
    image:
      'https://cdn.pixabay.com/photo/2011/07/25/23/39/finger-coral-tree-frog-8341_1280.jpg',
    imageAlt: 'An Australian green tree frog perched on a leaf',
  },
];
